apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-data-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-data
  template:
    metadata:
      labels:
        app: shared-data
    spec:
      volumes:
        - name: shared-data-volume
          persistentVolumeClaim:
            claimName: example-pvc
      containers:
        - name: multitool
          image: wbitt/network-multitool:latest
          volumeMounts:
            - name: shared-data-volume
              mountPath: /data

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "microk8s-hostpath"
  resources:
    requests:
      storage: 1Gi
