apiVersion: apps/v1
kind: Deployment
metadata:
  name: shared-data-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shared-data
  template:
    metadata:
      labels:
        app: shared-data
    spec:
      volumes:
        - name: shared-data-volume
          emptyDir: {}
      containers:
        - name: busybox
          image: busybox:latest
          command:
            - /bin/sh
            - -c
            - >
              while true;
              do echo "$(date) - Data written by busybox" >> /data/shared-file-busybox.txt;
              sleep 5;
              done;
          volumeMounts:
            - name: shared-data-volume
              mountPath: /data
        - name: multitool
          image: wbitt/network-multitool:latest
          command:
            - /bin/sh
            - -c
            - >
              while true;
              do cat /data/shared-file-busybox.txt;
